### ISSUE TITLE
FLCL Progressive英配版第六集字幕缺失

### ISSUE THREAD

**Issue by WeidiDeng** [SweetSub/SweetSub#24]
[这里](https://github.com/tastysugar/SweetSub/tree/master/FLCL%20Progressive%20(Dubbed))只有前五集的中英文字幕

**Comment by tastysugar** [comment]
[https://github.com/tastysugar/SweetSub/commit/c3e3a136261c86fcee9cfcd7830413ad505d123e](url)
done
