### ISSUE TITLE
缺少FLCL Alternative的分集版字幕

### ISSUE THREAD

**Issue by Pr0pHesyer** [SweetSub/SweetSub#27]
根据在dmhy中发布的分集版资源，说明是有制作分集字幕，但是并未发布到GitHub

**Comment by tastysugar** [comment]
BD 原盘本身是连在一起的编排，分集版是我们自己切的，方便把字幕任务分割成几个小部分慢慢来。
既然本身是没有分集版的片源，我们不会提供分集版字幕。

（Adult Swim 的片源是分集版，但是是英文配音的 WEB 源）

**Comment by tastysugar** [comment]
P.S. 我建议下载剧场版而不是分集版，因为后面剧场版的字幕比起分集版有修正。
