### ISSUE TITLE
能不能分享一下字体包。原来都不是宋体的吗？

### ISSUE THREAD

**Issue by RtYkk** [SweetSub/SweetSub#6]
![2019-06-14 22_02_04-Greenshot](https://user-images.githubusercontent.com/45971730/59514749-15c46b00-8ef0-11e9-9ec7-283524969772.jpg)
![2019-06-14 22_02_09-Greenshot](https://user-images.githubusercontent.com/45971730/59514759-1d840f80-8ef0-11e9-9c35-f4f9b0bc9ca5.jpg)
还是op歌词benla本来就是宋体，正片不是不需要字体包？

**Comment by Floatsuki** [comment]
（僅僅針對 Sarazanmai 的情況）
如果您在觀看的是由 SweetSub 在其他站點發布的內封版，那麼無需安裝字體，所有所需字體已封入 mkv ，直接使用 Potplayer 等播放器來播放就是正常的效果（如圖即是）。

**只有使用在 Github 發布的字幕文件手動搭配片源觀看時才需要額外安裝字體**，此時所需的字體詳見 [Sarazanmai 下的 README](https://github.com/tastysugar/SweetSub/tree/master/Sarazanmai#%E5%AD%97%E4%BD%93%E5%88%97%E8%A1%A8) 。

**Comment by tastysugar** [comment]
嗯，简单的来说，OP 用的是思源宋体，你现在看到的是正常的显示效果。
